language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - nightly

cache:
  cargo: true
  directories:
    - $HOME/kcov

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then which rustfmt || cargo install rustfmt-nightly; fi;
  - .ci/install-kcov.sh

addons:
  apt:
    packages:
      # packages required to compile kcov
      - texlive-base
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - libbfd-dev

before_script:
  - tex --version
  # Remove old build because travis cache them and this could be bad
  # for code coverage mesurement.
  - cargo clean

script:
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then cargo fmt -- --write-mode=diff; fi;
  - cargo build
  - cargo test

after_success:
  - .ci/coverage.sh
