language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - nightly

cache: cargo

install:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt

script:
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test
